sudo : required
services : 
  - docker

before_install: 
  - docker build -t andrejdock/docker-react -f Dockerfile.dev . 

  script:
    - docker run andrejdock/docker-react npm run test -- --coverage